version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: skilltree-postgres
    environment:
      POSTGRES_USER: skillTree
      POSTGRES_PASSWORD: password
      POSTGRES_DB: skillTree_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillTree -d skillTree_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: skilltree-redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: